import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const ScenarioToggle = ({ scenario, onScenarioChange }) => {
    return (_jsxs("div", { className: "bg-white rounded-lg border border-gray-200 p-4", children: [_jsxs("div", { className: "flex items-center gap-2 mb-3", children: [_jsx("span", { className: "text-sm font-semibold text-gray-700", children: "Scenario:" }), _jsx("span", { className: "text-xs text-gray-500", children: "(affects all forecasts)" })] }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsx("button", { onClick: () => onScenarioChange('best'), className: `flex-1 px-4 py-3 rounded-lg border-2 transition-all ${scenario === 'best'
                            ? 'border-green-500 bg-green-50'
                            : 'border-gray-200 bg-white hover:border-green-300'}`, children: _jsxs("div", { className: "flex items-center justify-center gap-2", children: [_jsx("span", { className: "text-2xl", children: "\uD83D\uDFE2" }), _jsxs("div", { className: "text-left", children: [_jsx("div", { className: `font-semibold ${scenario === 'best' ? 'text-green-700' : 'text-gray-700'}`, children: "Best Case" }), _jsx("div", { className: "text-xs text-gray-500", children: "+15% revenue, -5% costs" })] })] }) }), _jsx("button", { onClick: () => onScenarioChange('base'), className: `flex-1 px-4 py-3 rounded-lg border-2 transition-all ${scenario === 'base'
                            ? 'border-blue-500 bg-blue-50'
                            : 'border-gray-200 bg-white hover:border-blue-300'}`, children: _jsxs("div", { className: "flex items-center justify-center gap-2", children: [_jsx("span", { className: "text-2xl", children: "\uD83D\uDD35" }), _jsxs("div", { className: "text-left", children: [_jsx("div", { className: `font-semibold ${scenario === 'base' ? 'text-blue-700' : 'text-gray-700'}`, children: "Base Case" }), _jsx("div", { className: "text-xs text-gray-500", children: "Expected scenario" })] })] }) }), _jsx("button", { onClick: () => onScenarioChange('worst'), className: `flex-1 px-4 py-3 rounded-lg border-2 transition-all ${scenario === 'worst'
                            ? 'border-red-500 bg-red-50'
                            : 'border-gray-200 bg-white hover:border-red-300'}`, children: _jsxs("div", { className: "flex items-center justify-center gap-2", children: [_jsx("span", { className: "text-2xl", children: "\uD83D\uDD34" }), _jsxs("div", { className: "text-left", children: [_jsx("div", { className: `font-semibold ${scenario === 'worst' ? 'text-red-700' : 'text-gray-700'}`, children: "Worst Case" }), _jsx("div", { className: "text-xs text-gray-500", children: "-15% revenue, +10% costs" })] })] }) })] })] }));
};
export default ScenarioToggle;
