"""India AP (Purchase Invoice) register exports — Excel (openpyxl) and PDF (reportlab).

Both exports share the same column set:
Invoice # | Vendor Name | Vendor GSTIN | Invoice Date | Due Date | Taxable Amount (₹) |
CGST (₹) | SGST (₹) | IGST (₹) | GST Total (₹) | Total Amount (₹) | HSN/SAC | Payment Terms | Status
"""
from __future__ import annotations

import io
from typing import Any

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter
from reportlab.lib import colors
from reportlab.lib.pagesizes import landscape, A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

NAVY = "0A1628"  # bare hex — used directly by openpyxl fills
TEAL = "0FA3A3"

COLUMNS = [
    "Invoice #", "Vendor Name", "Vendor GSTIN", "Invoice Date", "Due Date",
    "Taxable Amount (₹)", "CGST (₹)", "SGST (₹)", "IGST (₹)", "GST Total (₹)",
    "Total Amount (₹)", "HSN/SAC", "Payment Terms", "Status",
]

FOOTER_TEXT = "Generated by FinReportAI by Gnanova Pro AI Technologies"


def _row(inv: dict[str, Any]) -> list[Any]:
    gst_total = float(inv.get("cgst_amount") or 0) + float(inv.get("sgst_amount") or 0) + float(inv.get("igst_amount") or 0)
    return [
        inv.get("invoice_number", ""),
        inv.get("vendor_name", ""),
        inv.get("vendor_gstin", "") or "",
        inv.get("invoice_date", ""),
        inv.get("due_date", ""),
        float(inv.get("subtotal") or 0),
        float(inv.get("cgst_amount") or 0),
        float(inv.get("sgst_amount") or 0),
        float(inv.get("igst_amount") or 0),
        gst_total,
        float(inv.get("total_amount") or 0),
        inv.get("hsn_sac", "") or "",
        inv.get("payment_terms", "") or "",
        inv.get("status", ""),
    ]


def build_excel(invoices: list[dict[str, Any]]) -> bytes:
    wb = Workbook()
    ws = wb.active
    ws.title = "India AP Invoices"

    header_fill = PatternFill(start_color=NAVY, end_color=NAVY, fill_type="solid")
    header_font = Font(bold=True, color="FFFFFF")
    alt_fill = PatternFill(start_color="F2F2F2", end_color="F2F2F2", fill_type="solid")
    currency_cols = {6, 7, 8, 9, 10, 11}  # 1-indexed: Taxable..Total Amount

    for col_idx, title in enumerate(COLUMNS, start=1):
        cell = ws.cell(row=1, column=col_idx, value=title)
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(horizontal="center", vertical="center")

    for row_idx, inv in enumerate(invoices, start=2):
        row = _row(inv)
        for col_idx, value in enumerate(row, start=1):
            cell = ws.cell(row=row_idx, column=col_idx, value=value)
            if col_idx in currency_cols:
                cell.number_format = '"₹"#,##0.00'
            if row_idx % 2 == 0:
                cell.fill = alt_fill

    totals_row = len(invoices) + 2
    ws.cell(row=totals_row, column=1, value="TOTAL").font = Font(bold=True)
    for col_idx in currency_cols:
        col_letter = get_column_letter(col_idx)
        total_cell = ws.cell(
            row=totals_row, column=col_idx,
            value=f"=SUM({col_letter}2:{col_letter}{totals_row - 1})" if invoices else 0,
        )
        total_cell.number_format = '"₹"#,##0.00'
        total_cell.font = Font(bold=True)

    footer_row = totals_row + 2
    ws.cell(row=footer_row, column=1, value=FOOTER_TEXT).font = Font(italic=True, size=9, color="666666")

    for col_idx, title in enumerate(COLUMNS, start=1):
        max_len = max([len(str(title))] + [len(str(_row(inv)[col_idx - 1])) for inv in invoices] or [0])
        ws.column_dimensions[get_column_letter(col_idx)].width = min(max(max_len + 3, 10), 40)

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


def build_pdf(*, invoices: list[dict[str, Any]], company_name: str, period: str) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=landscape(A4),
        topMargin=0.5 * inch, bottomMargin=0.5 * inch,
        leftMargin=0.4 * inch, rightMargin=0.4 * inch,
    )
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="GnanovaHeader", parent=styles["Normal"], textColor=colors.HexColor("#" + TEAL), fontSize=9))
    styles.add(ParagraphStyle(name="GnanovaTitle", parent=styles["Title"], textColor=colors.HexColor("#" + NAVY)))
    styles.add(ParagraphStyle(name="GnanovaSection", parent=styles["Heading2"], textColor=colors.HexColor("#" + NAVY)))

    story: list = []
    story.append(Paragraph("FinReportAI by Gnanova Pro AI Technologies", styles["GnanovaHeader"]))
    story.append(Paragraph(company_name or "Company", styles["GnanovaTitle"]))
    story.append(Paragraph("India AP Invoice Register — GST Summary", styles["Heading2"]))
    story.append(Paragraph(f"Period: {period}", styles["Normal"]))
    story.append(Spacer(1, 12))

    table_headers = [
        "Invoice #", "Vendor", "GSTIN", "Inv. Date", "Due Date",
        "Taxable", "CGST", "SGST", "IGST", "GST Total", "Total", "HSN/SAC", "Terms", "Status",
    ]
    data = [table_headers]
    for inv in invoices:
        r = _row(inv)
        data.append([
            r[0], r[1], r[2], r[3], r[4],
            f"{r[5]:,.2f}", f"{r[6]:,.2f}", f"{r[7]:,.2f}", f"{r[8]:,.2f}", f"{r[9]:,.2f}", f"{r[10]:,.2f}",
            r[11], r[12], r[13],
        ])

    table = Table(data, repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#" + NAVY)),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 7),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F2F2F2")]),
        ("ALIGN", (5, 1), (10, -1), "RIGHT"),
    ]))
    story.append(table)
    story.append(Spacer(1, 16))

    total_taxable = sum(float(i.get("subtotal") or 0) for i in invoices)
    total_cgst = sum(float(i.get("cgst_amount") or 0) for i in invoices)
    total_sgst = sum(float(i.get("sgst_amount") or 0) for i in invoices)
    total_igst = sum(float(i.get("igst_amount") or 0) for i in invoices)
    total_gst = total_cgst + total_sgst + total_igst
    total_value = sum(float(i.get("total_amount") or 0) for i in invoices)

    story.append(Paragraph("GST Summary", styles["GnanovaSection"]))
    summary_rows = [
        ["Total Taxable Amount", f"₹{total_taxable:,.2f}"],
        ["Total CGST", f"₹{total_cgst:,.2f}"],
        ["Total SGST", f"₹{total_sgst:,.2f}"],
        ["Total IGST", f"₹{total_igst:,.2f}"],
        ["Total GST", f"₹{total_gst:,.2f}"],
        ["Total Invoice Value", f"₹{total_value:,.2f}"],
    ]
    summary_table = Table(summary_rows, colWidths=[2.5 * inch, 2 * inch])
    summary_table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("BACKGROUND", (0, -1), (-1, -1), colors.HexColor("#" + TEAL)),
        ("TEXTCOLOR", (0, -1), (-1, -1), colors.white),
        ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
    ]))
    story.append(summary_table)
    story.append(Spacer(1, 16))
    story.append(Paragraph("This report is generated for GST reconciliation purposes.", styles["Normal"]))
    story.append(Paragraph(FOOTER_TEXT, ParagraphStyle(name="Footer", parent=styles["Normal"], fontSize=8, textColor=colors.grey)))

    doc.build(story)
    return buf.getvalue()
